# Generated by Django 4.1.3 on 2022-11-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_user_register_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
