# Generated by Django 4.1.3 on 2022-11-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_user_register_contact_user_register_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
