# Generated by Django 4.1.3 on 2022-11-25 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_user_register_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_attendance_monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('contact', models.IntegerField(max_length=20)),
                ('login_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
