# Generated by Django 4.1.3 on 2022-11-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_user_attendance_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_attendance_monitor',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
