# Generated by Django 4.1.3 on 2022-11-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_user_attendance_monitor_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='users_id',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
