# Generated by Django 4.1.3 on 2022-11-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_user_register_users_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_register',
            old_name='users_id',
            new_name='member_id',
        ),
    ]
