# Generated by Django 4.1.3 on 2022-11-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_rename_users_id_user_register_member_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.CharField(help_text='you have logged in today', max_length=50)),
            ],
        ),
    ]
