# Generated by Django 4.1.3 on 2022-11-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_user_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_notifications',
            name='person',
            field=models.TextField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_notifications',
            name='notify',
            field=models.CharField(max_length=50),
        ),
    ]
