# Generated by Django 4.1.3 on 2022-11-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_user_notifications_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_notifications',
            name='person',
            field=models.TextField(max_length=50),
        ),
    ]
