# Generated by Django 4.1.3 on 2022-12-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_membership_name_of_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='discount_percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='discounted_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='original_price',
            field=models.IntegerField(),
        ),
    ]
