# Generated by Django 4.1.3 on 2022-12-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_alter_membership_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='discount_percentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='discounted_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='original_price',
            field=models.IntegerField(null=True),
        ),
    ]
